pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "org.jetbrains.kotlin.android") {
                useVersion("1.9.22")
            }
        }
    }
}

rootProject.name = 'inexiamobile'
include ':app'
includeBuild('../node_modules/@react-native/gradle-plugin')